project:
  type: website

website:
  title: "PL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: publications.qmd
        text: Publications
      - href: codes.qmd
        text: Codes

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true



